[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SRDP Database & API"
authors = [
    {name = "Evan Jones", email = "evan.a.jones3@gmail.com"},
    {name = "Harriet Goers", email = "hgoers@umd.edu"}
]
dynamic = ["version", "description"]