"""fix updates

Revision ID: 26579ae2fca1
Revises: e646e83e746a
Create Date: 2021-09-04 15:08:24.720312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26579ae2fca1'
down_revision = 'e646e83e746a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    # ### end Alembic commands ###
