"""add media info to post

Revision ID: 3338863d2def
Revises: f6707f4404ea
Create Date: 2021-07-17 12:26:18.672587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3338863d2def'
down_revision = 'f6707f4404ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('media_class', sa.String(length=6), nullable=True))
    op.add_column('post', sa.Column('media_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'media_type')
    op.drop_column('post', 'media_class')
    # ### end Alembic commands ###
