"""add media_url to posts

Revision ID: 43533f276ba5
Revises: fbb28f6dd342
Create Date: 2021-07-06 17:38:49.554162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43533f276ba5'
down_revision = 'fbb28f6dd342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('media_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'media_url')
    # ### end Alembic commands ###
