"""add is_comment to posts

Revision ID: 4529f52b30e9
Revises: 9732bf5d6a17
Create Date: 2021-07-13 15:59:56.574360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4529f52b30e9'
down_revision = '9732bf5d6a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_comment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_comment')
    # ### end Alembic commands ###
