"""add AuditMixin to User

Revision ID: 461e80f739f9
Revises: 924e931f51f3
Create Date: 2021-06-30 13:53:37.399113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461e80f739f9'
down_revision = '924e931f51f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_modified_at'), 'user', ['modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_modified_at'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_column('user', 'modified_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
