"""add profile pic and name to user

Revision ID: 700ec1da57fe
Revises: f6707f4404ea
Create Date: 2021-07-21 14:41:10.300312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700ec1da57fe'
down_revision = 'f6707f4404ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('profile_pic', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
