"""fix repost tablename typo

Revision ID: 8aebe6402077
Revises: fa0c0b4ba20e
Create Date: 2021-07-28 19:07:24.891849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aebe6402077'
down_revision = 'fa0c0b4ba20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reposts',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.Column('repost_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repost_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('root_id', 'repost_id')
    )
    op.create_index(op.f('ix_reposts_created_at'), 'reposts', ['created_at'], unique=False)
    op.create_index(op.f('ix_reposts_modified_at'), 'reposts', ['modified_at'], unique=False)
    op.drop_table('resposts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resposts',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('modified_at', sa.DATETIME(), nullable=True),
    sa.Column('root_id', sa.INTEGER(), nullable=False),
    sa.Column('repost_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['repost_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('root_id', 'repost_id')
    )
    op.drop_index(op.f('ix_reposts_modified_at'), table_name='reposts')
    op.drop_index(op.f('ix_reposts_created_at'), table_name='reposts')
    op.drop_table('reposts')
    # ### end Alembic commands ###
