"""comments

Revision ID: 9732bf5d6a17
Revises: 43533f276ba5
Create Date: 2021-07-12 19:30:45.031544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9732bf5d6a17'
down_revision = '43533f276ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'comment_id')
    )
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_modified_at'), 'comments', ['modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_modified_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
