"""add is_repost to posts

Revision ID: e646e83e746a
Revises: 8aebe6402077
Create Date: 2021-07-30 13:02:32.457599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e646e83e746a'
down_revision = '8aebe6402077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_repost', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_repost')
    # ### end Alembic commands ###
