"""add last_updates_read_time

Revision ID: f6707f4404ea
Revises: 4529f52b30e9
Create Date: 2021-07-14 11:43:10.911085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6707f4404ea'
down_revision = '4529f52b30e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_updates_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_updates_read_time')
    # ### end Alembic commands ###
