"""reposts

Revision ID: fa0c0b4ba20e
Revises: 25a77836bde8
Create Date: 2021-07-27 15:57:58.764024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0c0b4ba20e'
down_revision = '25a77836bde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resposts',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.Column('repost_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repost_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('root_id', 'repost_id')
    )
    op.create_index(op.f('ix_resposts_created_at'), 'resposts', ['created_at'], unique=False)
    op.create_index(op.f('ix_resposts_modified_at'), 'resposts', ['modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resposts_modified_at'), table_name='resposts')
    op.drop_index(op.f('ix_resposts_created_at'), table_name='resposts')
    op.drop_table('resposts')
    # ### end Alembic commands ###
