"""Add AuditMixin to Posts

Revision ID: fbb28f6dd342
Revises: 461e80f739f9
Create Date: 2021-06-30 14:25:05.930331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb28f6dd342'
down_revision = '461e80f739f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('post', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_post_created_at'), 'post', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_modified_at'), 'post', ['modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_modified_at'), table_name='post')
    op.drop_index(op.f('ix_post_created_at'), table_name='post')
    op.drop_column('post', 'modified_at')
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
